keys:
  - &nily  age16cjsexaheqlrd32d5cpxx9km0llnn4l9g0gwte6gcwf2tlqyrg3sgl8myx
  # - &nixi  age1REEMPLAZAR_CUANDO_TENGAS_NIXI

creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *nily

  - path_regex: secrets/nily\.yaml$
    key_groups:
      - age:
          - *nily
