keys:
  - &nily  age1pfmg7p93vwxexgpl7zwtfq8q6v68cescgwcy0qznwuz7v3g05y4stmxhxu
  - &nixi  age1gkhhgjn876sqcc3n6tn246z9v9jk0wq7fuekwxzqq3p0lgndsq8szy9vr2

creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *nily
          - *nixi

  - path_regex: secrets/nily\.yaml$
    key_groups:
      - age:
          - *nily
