# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4f716ea1-6ec8-4314-905c-87a5591b26b0";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D948-6A0E";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4f716ea1-6ec8-4314-905c-87a5591b26b0";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/4f716ea1-6ec8-4314-905c-87a5591b26b0";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/4f716ea1-6ec8-4314-905c-87a5591b26b0";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/4f716ea1-6ec8-4314-905c-87a5591b26b0";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/4f716ea1-6ec8-4314-905c-87a5591b26b0";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/var/lib/libvirt" =
    { device = "/dev/disk/by-uuid/4f716ea1-6ec8-4314-905c-87a5591b26b0";
      fsType = "btrfs";
      options = [ "subvol=@libvirt" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/4f716ea1-6ec8-4314-905c-87a5591b26b0";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0afa6f7e-0a09-475c-a213-c9f9171b2318"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
