# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Root - sistema base
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/20cd2adb-f872-4d51-afeb-fc50ae62ab78";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" "space_cache=v2" ];
    };

  # Boot - partición EFI
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/91E2-1637";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Home - directorios de usuarios
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/20cd2adb-f872-4d51-afeb-fc50ae62ab78";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  # Nix - store de paquetes
  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/20cd2adb-f872-4d51-afeb-fc50ae62ab78";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  # Tmp - archivos temporales
  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/20cd2adb-f872-4d51-afeb-fc50ae62ab78";
      fsType = "btrfs";
      options = [ "subvol=@tmp" "compress=zstd" "noatime" ];
    };

  # Var - datos variables
  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/20cd2adb-f872-4d51-afeb-fc50ae62ab78";
      fsType = "btrfs";
      options = [ "subvol=@var" "compress=zstd" "noatime" ];
    };

  # Cache - cachés del sistema
  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/20cd2adb-f872-4d51-afeb-fc50ae62ab78";
      fsType = "btrfs";
      options = [ "subvol=@cache" "compress=zstd" "noatime" ];
    };

  # Libvirt - VMs (sin COW para mejor performance)
  fileSystems."/var/lib/libvirt" =
    { device = "/dev/disk/by-uuid/20cd2adb-f872-4d51-afeb-fc50ae62ab78";
      fsType = "btrfs";
      options = [ "subvol=@libvirt" "compress=zstd" "noatime" "nodatacow" ];
    };

  # Log - logs del sistema
  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/20cd2adb-f872-4d51-afeb-fc50ae62ab78";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd" "noatime" ];
    };

  # Swap
  swapDevices =
    [ { device = "/dev/disk/by-uuid/90a59173-08e9-47b9-88f5-ee68ae1e68fc"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
